### ISSUE TITLE
Unable to play new episodes

### ISSUE THREAD

**Issue by bomaderry** [xbmc-catchuptv-au/plugin.video.plus7#1726]
Unable to play new content, old episodes work fine. Tried various shows and the same result.

08:51:20 T:9856  NOTICE: [Plus7 v3.1.1] XBMC 16.1 running on Windows
08:51:20 T:9856  NOTICE: [Plus7 v3.1.1] Showing series list
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Buzz (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: News (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series Home and Away Extras (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: BuzzFeed Picks (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Finance (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Cute Pets (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Health (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Celeb News (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Travel (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Interviews (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Comedy (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Editor's Picks (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Epic Fails (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Style (hide extras)
08:51:21 T:9856  NOTICE: [Plus7 v3.1.1] Skipping series TV Snax: Food (hide extras)
08:51:28 T:14604  NOTICE: [Plus7 v3.1.1] XBMC 16.1 running on Windows
08:51:28 T:14604  NOTICE: [Plus7 v3.1.1] Showing programs list for autv-plus7-selling-houses-australia
08:51:30 T:13856  NOTICE: [Plus7 v3.1.1] XBMC 16.1 running on Windows
08:51:30 T:13856  NOTICE: [Plus7 v3.1.1] Fetching program information for: 33471705
08:51:30 T:13856  NOTICE: [Plus7 v3.1.1] Fetching URL: https://api.brightcove.com/services/library?command=find_video_by_reference_id&reference_id=33471705&media_delivery=HTTP_IOS&video_fields=id,name,shortDescription,videoStillURL,length,FLVURL,captioning&token=BMG-nlpt1dDQcdqz-EIBAUNRGtXnLQv-gbltLyHgproxck0YUZfnkA..
08:51:31 T:13856  NOTICE: [Plus7 v3.1.1] No subtitles available for this program
08:51:31 T:13856  NOTICE: [Plus7 v3.1.1] Using native HTTPS HLS stream handling...
08:51:31 T:13856  NOTICE: [Plus7 v3.1.1] Attempting to play: Selling Houses Australia: Fri 9 Dec, season 6 episode 7
08:51:31 T:924  NOTICE: DVDPlayer: Opening: https://yahoo7p-a.akamaihd.net/2376984108001/201612/93/2376984108001_5241107058001_5241093784001.m3u8?pubId=2376984108001&videoId=5241093784001
08:51:31 T:924 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
08:51:31 T:13864  NOTICE: Creating InputStream
08:51:31 T:13864  NOTICE: Creating Demuxer
08:51:32 T:13864   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
08:51:32 T:13864  NOTICE: CDVDPlayer::OnExit()
08:51:32 T:924   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plus7/?program_id=33471705]

**Comment by adoxa** [comment]
I'm not a Kodi user, but I've come across the same problem. It seems PLUS7 has switched to SAMPLE-AES encryption, which FFmpeg (and hence Kodi) does not support. There is a program that does [decrypt it](https://github.com/selsta/hlsdl), but it won't work with the `skd:` URI to get the key. Okay, time to try [AdobeHDS](https://raw.github.com/K-S-V/Scripts/blob/master/AdobeHDS.php) but that didn't work either, as it uses FlashAccess DRM.

**Comment by glennguy** [comment]
It looks like all the new episodes are protected by either HDS, Playready, Fairplay and Widevine. We can get Widevine working in Kodi 17. If I can find the time, hopefully this weekend.

**Comment by munecito** [comment]
Hello. 

Same problem here with version 3.1.1 I can't watch some shows in Kodi. For example the chase it says opening and then gives an error

**Comment by andybotting** [comment]
Widevine DRM was implemented, but we're now moving to 7plus, which doesn't require DRM, so closing issue.
