### ISSUE TITLE
New Plus7 App

### ISSUE THREAD

**Issue by raaaachy** [xbmc-catchuptv-au/plugin.video.plus7#1911]
The app has recently changed (I had to install the new one on my phone so it’s a whole new, app not just an update) and no some shows aren’t on there e.g. Home and Away

**Comment by andybotting** [comment]
Yeah, we've just got a new version for 7plus published in our development repository.

The instructions for setting up the development repository are here:
http://aussieaddons.com/development/

Would love your feedback.

**Comment by raaaachy** [comment]
You guys are amazing, thanks!!
