### ISSUE TITLE
7Plus will not play on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by PeterBeckwith** [xbmc-catchuptv-au/plugin.video.plus7#1912]
Using: latest Kodi 17.6 from team-xbmc stable repo, latest Ubuntu 16.04.3
Playback fails silently after the line 'NOTICE: Creating Demuxer', see log file
The URL in the subsequent 'ERROR: Open' line can be used (in FireFox) to successfully download a manifest.mpd file but apparently the script is unable to parse it.

[7plus fails on ubuntu.txt](https://github.com/xbmc-catchuptv-au/plugin.video.plus7/files/1628684/7plus.fails.on.ubuntu.txt)
[kodi.log](https://github.com/xbmc-catchuptv-au/plugin.video.plus7/files/1628685/kodi.log)

**Comment by glennguy** [comment]
Hi @PeterBeckwith 

Thanks for the details!

We might get a better idea about exactly what's going on if you could enable debug logging in Kodi.

My first thought is that the inputstream.adaptive addon may need updating. There's a menu item for this in the 7plus settings but the builds supplied are for LibreELEC and might not work in ubuntu. I can see that this has happened to you in the log: ```06:30:05.421 T:140392477477248   ERROR: Unable to load /home/beckwith/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.10, reason: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/beckwith/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.10)```

It's something I need to sort out (only allowing updates to inputstream.adaptive on LibreELEC as opposed to all linux distros)

Luckily, there's an up to date version in the ubuntu repo.

I'm no linux expert but this should get you sorted:
```
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi-inputstream-adaptive
```

**Comment by PeterBeckwith** [comment]
That was it. I already had the repo but not the inputstream binary. It required a reboot after installation, and now the plugin is fine.

Thanks for the help
Peter

Sent from Blue<http://www.bluemail.me/r?b=11745>
On 14 Jan. 2018, at 1:57 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @PeterBeckwith<https://github.com/peterbeckwith>

Thanks for the details!

We might get a better idea about exactly what's going on if you could enable debug logging in Kodi.

My first thought is that the inputstream.adaptive addon may need updating. There's a menu item for this in the 7plus settings but the builds supplied are for LibreELEC and might not work in ubuntu. I can see that this has happened to you in the log: 06:30:05.421 T:140392477477248 ERROR: Unable to load /home/beckwith/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.10, reason: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/beckwith/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.0.10)

It's something I need to sort out (only allowing updates to inputstream.adaptive on LibreELEC as opposed to all linux distros)

Luckily, there's an up to date version in the ubuntu repo.

I'm no linux expert but this should get you sorted:

sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi-inputstream-adaptive

**Comment by glennguy** [comment]
Awesome, great to hear! I'll close this issue now.

**Comment by bortoelnino** [comment]
I had this issue too on ubuntu 16.04. I ran the apt-get steps above but it seemed like the included libre-elec libraries caused a conflict and loaded before the system inputstream-adaptive libraries. 

Playback didn't work (I got the GLIBCXX_3.4.22 error when starting kodi) until I uninstalled the inputstream-adaptive plugin from kodi, and then restarted. 

Thanks for an awesome set of plugins!
